#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 04, 2019 05:49:48 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()
    global gui_srcpcbxsize
    gui_srcpcbxsize = tk.StringVar()
    global gui_srcpcbysize
    gui_srcpcbysize = tk.StringVar()
    global gui_srcformat
    gui_srcformat = tk.StringVar()
    global gui_3dp_pcbxorig
    gui_3dp_pcbxorig = tk.StringVar()
    global gui_3dp_pcbyorig
    gui_3dp_pcbyorig = tk.StringVar()
    global gui_3dp_pcbzorig
    gui_3dp_pcbzorig = tk.StringVar()
    global gui_3dp_pcbxcount
    gui_3dp_pcbxcount = tk.StringVar()
    global gui_3dp_pcbycount
    gui_3dp_pcbycount = tk.StringVar()
    global gui_3dp_pcbxfurthest
    gui_3dp_pcbxfurthest = tk.StringVar()
    global gui_3dp_pcbyfurthest
    gui_3dp_pcbyfurthest = tk.StringVar()
    global che58
    che58 = tk.IntVar()
    global spinbox
    spinbox = tk.StringVar()

def gui_3dp_updatedcount():
    print('gerber2gcode_gui_support.gui_3dp_updatedcount')
    sys.stdout.flush()

def gui_3dp_updatedfurthest():
    print('gerber2gcode_gui_support.gui_3dp_updatedfurthest')
    sys.stdout.flush()

def gui_3dp_updatedorigin():
    print('gerber2gcode_gui_support.gui_3dp_updatedorigin')
    sys.stdout.flush()

def gui_button_clearlog():
    print('gerber2gcode_gui_support.gui_button_clearlog')
    sys.stdout.flush()

def gui_button_exit():
    print('gerber2gcode_gui_support.gui_button_exit')
    sys.stdout.flush()

def gui_button_importGerber():
    print('gerber2gcode_gui_support.gui_button_importGerber')
    sys.stdout.flush()

def gui_button_loadsettings():
    print('gerber2gcode_gui_support.gui_button_loadsettings')
    sys.stdout.flush()

def gui_button_resetsettings():
    print('gerber2gcode_gui_support.gui_button_resetsettings')
    sys.stdout.flush()

def gui_button_savesettings():
    print('gerber2gcode_gui_support.gui_button_savesettings')
    sys.stdout.flush()

def gui_preview_changesides():
    print('gerber2gcode_gui_support.gui_preview_changesides')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gerber2gcode_gui
    gerber2gcode_gui.vp_start_gui()




