#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 02, 2019 04:38:40 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x580+622+370
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 800 600
    wm minsize $top 800 600
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "GERBER2GCODE - Solder paste dispenser for 3D printer"
    vTcl:DefineAlias "$top" "main_window" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    vTcl:DefineAlias "$site_3_0" "gui_menubar" vTcl:WidgetProc "" 1
    $site_3_0 add cascade \
        -menu "$site_3_0.men51" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label File 
    menu $site_3_0.men51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men51 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#gui_button_exit} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Exit 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo70 \
        -width 804 -height 606 -takefocus {} 
    vTcl:DefineAlias "$top.tNo70" "gui_notebook" vTcl:WidgetProc "main_window" 1
    frame $top.tNo70.t0 \
        -relief groove -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo70.t0" "gui_notebook_t0" vTcl:WidgetProc "main_window" 1
    $top.tNo70 add $top.tNo70.t0 \
        -padding 0 -sticky nsew -state normal -text Main -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo70.t0
    labelframe $site_4_0.lab75 \
        -font TkDefaultFont -foreground black -text Preview \
        -background $vTcl(actual_gui_bg) -height 470 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 420 
    vTcl:DefineAlias "$site_4_0.lab75" "gui_labelframe_preview" vTcl:WidgetProc "main_window" 1
    set site_5_0 $site_4_0.lab75
    canvas $site_5_0.can64 \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 400 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #c4c4c4 \
        -selectforeground black -width 400 
    vTcl:DefineAlias "$site_5_0.can64" "gui_preview_canvas" vTcl:WidgetProc "main_window" 1
    button $site_5_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command gui_preview_button_topside \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Top side} 
    vTcl:DefineAlias "$site_5_0.but49" "gui_preview_button_topside" vTcl:WidgetProc "main_window" 1
    button $site_5_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) \
        -command gui_preview_button_bottomside -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Bottom side} 
    vTcl:DefineAlias "$site_5_0.but50" "gui_preview_button_bottomside" vTcl:WidgetProc "main_window" 1
    place $site_5_0.can64 \
        -in $site_5_0 -x 10 -y 20 -width 400 -relwidth 0 -height 400 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but49 \
        -in $site_5_0 -x 120 -y 420 -width 87 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but50 \
        -in $site_5_0 -x 210 -y 420 -width 87 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab52 \
        -font TkDefaultFont -foreground black -text Import \
        -background $vTcl(actual_gui_bg) -height 85 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab52" "gui_labelframe_import" vTcl:WidgetProc "main_window" 1
    set site_5_0 $site_4_0.lab52
    button $site_5_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command gui_button_importGerber \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Import GERBER file...} 
    vTcl:DefineAlias "$site_5_0.but53" "gui_button_importGerber" vTcl:WidgetProc "main_window" 1
    place $site_5_0.but53 \
        -in $site_5_0 -x 20 -y 30 -width 147 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab43 \
        -font TkDefaultFont -foreground black -text {PCB geometry} \
        -background $vTcl(actual_gui_bg) -height 365 -width 350 
    vTcl:DefineAlias "$site_4_0.lab43" "Labelframe1" vTcl:WidgetProc "main_window" 1
    set site_5_0 $site_4_0.lab43
    label $site_5_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {PCB thickness (mm)} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label1" vTcl:WidgetProc "main_window" 1
    spinbox $site_5_0.spi49 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -format %1.2f -from 0.1 -highlightbackground black \
        -highlightcolor black -increment 0.1 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable pcbthickness -to 2.0 
    vTcl:DefineAlias "$site_5_0.spi49" "gui_main_pcbthickness" vTcl:WidgetProc "main_window" 1
    labelframe $site_5_0.lab59 \
        -font TkDefaultFont -foreground black -text {Multi PCB} \
        -background $vTcl(actual_gui_bg) -height 85 -width 150 
    vTcl:DefineAlias "$site_5_0.lab59" "Labelframe2" vTcl:WidgetProc "main_window" 1
    set site_6_0 $site_5_0.lab59
    spinbox $site_6_0.spi60 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -format %1.0f -from 1.0 -highlightbackground black \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable pcbxcount -to 10.0 
    vTcl:DefineAlias "$site_6_0.spi60" "gui_main_pcbxcount" vTcl:WidgetProc "main_window" 1
    label $site_6_0.lab61 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {PCBs on X axis} 
    vTcl:DefineAlias "$site_6_0.lab61" "Label1" vTcl:WidgetProc "main_window" 1
    label $site_6_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PCBs on Y axis} 
    vTcl:DefineAlias "$site_6_0.lab62" "Label1" vTcl:WidgetProc "main_window" 1
    spinbox $site_6_0.spi63 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -format %1.0f -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable pcbycount -to 10.0 
    vTcl:DefineAlias "$site_6_0.spi63" "gui_main_pcbycount" vTcl:WidgetProc "main_window" 1
    place $site_6_0.spi60 \
        -in $site_6_0 -x 100 -y 30 -width 35 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab61 \
        -in $site_6_0 -x 10 -y 30 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab62 \
        -in $site_6_0 -x 10 -y 50 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.spi63 \
        -in $site_6_0 -x 100 -y 50 -width 35 -height 19 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab64 \
        -font TkDefaultFont -foreground black -text {PCB origin} \
        -background $vTcl(actual_gui_bg) -height 85 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 170 
    vTcl:DefineAlias "$site_5_0.lab64" "Labelframe2" vTcl:WidgetProc "main_window" 1
    set site_6_0 $site_5_0.lab64
    spinbox $site_6_0.spi60 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -format %1.1f -highlightbackground black -highlightcolor black \
        -increment 0.1 -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable pcbxorig -to 100.0 
    vTcl:DefineAlias "$site_6_0.spi60" "gui_main_pcbxorig" vTcl:WidgetProc "main_window" 1
    label $site_6_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {On X axis (mm)} 
    vTcl:DefineAlias "$site_6_0.lab61" "Label1" vTcl:WidgetProc "main_window" 1
    label $site_6_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {On Y axis (mm)} 
    vTcl:DefineAlias "$site_6_0.lab62" "Label1" vTcl:WidgetProc "main_window" 1
    spinbox $site_6_0.spi63 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -format %1.1f -highlightbackground black -highlightcolor black \
        -increment 0.1 -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable pcbyorig -to 100.0 
    vTcl:DefineAlias "$site_6_0.spi63" "gui_main_pcbyorig" vTcl:WidgetProc "main_window" 1
    place $site_6_0.spi60 \
        -in $site_6_0 -x 100 -y 30 -width 55 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab61 \
        -in $site_6_0 -x 10 -y 30 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab62 \
        -in $site_6_0 -x 10 -y 50 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.spi63 \
        -in $site_6_0 -x 100 -y 50 -width 55 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 10 -y 30 -width 124 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.spi49 \
        -in $site_5_0 -x 130 -y 30 -width 55 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab59 \
        -in $site_5_0 -x 10 -y 80 -width 150 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab64 \
        -in $site_5_0 -x 170 -y 80 -width 170 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab75 \
        -in $site_4_0 -x 370 -y 10 -width 420 -relwidth 0 -height 470 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 10 -y 10 -width 350 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab43 \
        -in $site_4_0 -x 10 -y 100 -width 350 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo70.t3 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo70.t3" "gui_notebook_t1" vTcl:WidgetProc "main_window" 1
    $top.tNo70 add $top.tNo70.t3 \
        -padding 0 -sticky nsew -state normal -text {G-code settings} \
        -image {} -compound none -underline -1 
    set site_4_1  $top.tNo70.t3
    labelframe $site_4_1.lab56 \
        -font TkDefaultFont -foreground black -text {Initial settings} \
        -background $vTcl(actual_gui_bg) -height 265 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 380 
    vTcl:DefineAlias "$site_4_1.lab56" "gui_gcode_labelframe_initial" vTcl:WidgetProc "main_window" 1
    set site_5_0 $site_4_1.lab56
    checkbutton $site_5_0.che58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Auto-home (G28)} -variable che58 
    vTcl:DefineAlias "$site_5_0.che58" "gui_checkbutton_gcode_autohome" vTcl:WidgetProc "main_window" 1
    entry $site_5_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent63" "Entry1" vTcl:WidgetProc "main_window" 1
    spinbox $site_5_0.spi64 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable spinbox -to 20.0 
    vTcl:DefineAlias "$site_5_0.spi64" "Spinbox1" vTcl:WidgetProc "main_window" 1
    place $site_5_0.che58 \
        -in $site_5_0 -x 10 -y 30 -width 211 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent63 \
        -in $site_5_0 -x 80 -y 120 -anchor nw -bordermode ignore 
    place $site_5_0.spi64 \
        -in $site_5_0 -x 320 -y 30 -width 45 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_1.lab57 \
        -font TkDefaultFont -foreground black -text {Final settings} \
        -background $vTcl(actual_gui_bg) -height 165 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 380 
    vTcl:DefineAlias "$site_4_1.lab57" "gui_gcode_labelframe_final" vTcl:WidgetProc "main_window" 1
    button $site_4_1.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load settings} 
    vTcl:DefineAlias "$site_4_1.but60" "gui_gcode_button_load" vTcl:WidgetProc "main_window" 1
    button $site_4_1.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Save settings} 
    vTcl:DefineAlias "$site_4_1.but61" "gui_gcode_button_save" vTcl:WidgetProc "main_window" 1
    button $site_4_1.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reset settings} 
    vTcl:DefineAlias "$site_4_1.but62" "gui_gcode_button_reset" vTcl:WidgetProc "main_window" 1
    place $site_4_1.lab56 \
        -in $site_4_1 -x 10 -y 40 -width 380 -relwidth 0 -height 265 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab57 \
        -in $site_4_1 -x 410 -y 40 -width 380 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but60 \
        -in $site_4_1 -x 10 -y 10 -width 97 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but61 \
        -in $site_4_1 -x 110 -y 10 -width 97 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but62 \
        -in $site_4_1 -x 690 -y 10 -width 97 -height 24 -anchor nw \
        -bordermode ignore 
    frame $top.tNo70.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo70.t1" "gui_notebook_t2" vTcl:WidgetProc "main_window" 1
    $top.tNo70 add $top.tNo70.t1 \
        -padding 0 -sticky nsew -state normal -text {3D printer} -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo70.t1
    frame $top.tNo70.t2 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo70.t2" "gui_notebook_t3" vTcl:WidgetProc "main_window" 1
    $top.tNo70 add $top.tNo70.t2 \
        -padding 0 -sticky nsew -state normal -text Log -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo70.t2
    text $site_4_3.tex74 \
        -background white -exportselection 0 -font TkTextFont \
        -foreground black -height 504 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 774 -wrap word 
    .top42.tNo70.t2.tex74 configure -font "TkTextFont"
    .top42.tNo70.t2.tex74 insert end text
    vTcl:DefineAlias "$site_4_3.tex74" "gui_log_window" vTcl:WidgetProc "main_window" 1
    button $site_4_3.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command gui_button_clearlog \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Clear log} 
    vTcl:DefineAlias "$site_4_3.but76" "gui_button_clearlog" vTcl:WidgetProc "main_window" 1
    place $site_4_3.tex74 \
        -in $site_4_3 -x 10 -y 40 -width 774 -relwidth 0 -height 504 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but76 \
        -in $site_4_3 -x 10 -y 10 -width 77 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo70 \
        -in $top -x 0 -y 0 -width 804 -relwidth 0 -height 606 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

