#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 02, 2019 04:15:26 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global spinbox
    spinbox = tk.StringVar()
    global che58
    che58 = tk.IntVar()

def gui_button_clearlog():
    print('gerber2gcode_gui_support.gui_button_clearlog')
    sys.stdout.flush()

def gui_button_exit():
    print('gerber2gcode_gui_support.gui_button_exit')
    sys.stdout.flush()

def gui_button_importGerber():
    print('gerber2gcode_gui_support.gui_button_importGerber')
    sys.stdout.flush()

def gui_preview_button_bottomside():
    print('gerber2gcode_gui_support.gui_preview_button_bottomside')
    sys.stdout.flush()

def gui_preview_button_topside():
    print('gerber2gcode_gui_support.gui_preview_button_topside')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gerber2gcode_gui
    gerber2gcode_gui.vp_start_gui()




